In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('imdb.csv')
data.head()

,Name,Date,Rate,Votes,Genre,Duration,Type,Certificate,Episodes,Nudity,Violence,Profanity,Alcohol,Frightening
0,No Time to Die,2021,7.6,"107,163","Action, Adventure, Thriller",163,Film,PG-13,-,Mild,Moderate,Mild,Mild,Moderate
1,The Guilty,2021,6.3,"64,375","Crime, Drama, Thriller",90,Film,R,-,None,None,Severe,None,Moderate
2,The Many Saints of Newark,2021,6.4,"27,145","Crime, Drama",120,Film,R,-,Moderate,Severe,Severe,Moderate,Moderate
3,Venom: Let There Be Carnage,2021,6.4,"30,443","Action, Adventure, Sci-Fi",97,Film,PG-13,-,None,Moderate,Moderate,Mild,Moderate
4,Dune,2021,8.3,"84,636","Action, Adventure, Drama",155,Film,PG-13,-,None,Moderate,None,Mild,Moderate

In [3]:
data.shape

(6178, 14)

In [4]:
data.sample(5)

,Name,Date,Rate,Votes,Genre,Duration,Type,Certificate,Episodes,Nudity,Violence,Profanity,Alcohol,Frightening
556,The Matrix Reloaded,2003,7.2,"544,760","Action, Sci-Fi",138,Film,(Banned),-,Moderate,Moderate,Moderate,Mild,Moderate
2335,Homefront,2013,6.5,"115,503","Action, Crime, Thriller",100,Film,R,-,Mild,Severe,Severe,Moderate,Moderate
2583,Sleepless in Seattle,1993,6.8,"167,456","Comedy, Drama, Romance",105,Film,PG,-,Mild,None,Mild,Mild,None
143,Scream,2022,No Rate,No Votes,"Horror, Mystery, Thriller",120,Film,None,-,No Rate,No Rate,No Rate,No Rate,No Rate
2450,Needle in a Timestack,2021,3.7,185,"Drama, Fantasy, Romance",111,Film,R,-,No Rate,No Rate,No Rate,No Rate,No Rate

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6178 entries, 0 to 6177
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         6178 non-null   object
 1   Date         6178 non-null   int64
 2   Rate         6178 non-null   object
 3   Votes        6178 non-null   object
 4   Genre        6178 non-null   object
 5   Duration     6178 non-null   object
 6   Type         6178 non-null   object
 7   Certificate  6178 non-null   object
 8   Episodes     6178 non-null   object
 9   Nudity       6178 non-null   object
 10  Violence     6178 non-null   object
 11  Profanity    6178 non-null   object
 12  Alcohol      6178 non-null   object
 13  Frightening  6178 non-null   object
dtypes: int64(1), object(13)
memory usage: 675.8+ KB

In [6]:
data.isnull().sum()

Name           0
Date           0
Rate           0
Votes          0
Genre          0
Duration       0
Type           0
Certificate    0
Episodes       0
Nudity         0
Violence       0
Profanity      0
Alcohol        0
Frightening    0
dtype: int64

In [10]:
data.describe()

              Date
count  6178.000000
mean   2005.952574
std      15.910248
min    1922.000000
25%    1998.000000
50%    2011.000000
75%    2019.000000
max    2023.000000

In [11]:
data.describe(include='object')

,Name,Rate,Votes,Genre,Duration,Type,Certificate,Episodes,Nudity,Violence,Profanity,Alcohol,Frightening
count,6178,6178,6178,6178,6178,6178,6178,6178,6178,6178,6178,6178,6178
unique,4820,77,4802,377,203,2,23,284,5,5,5,5,5
top,King Kong,7.3,No Votes,Comedy,60,Film,R,-,Mild,Moderate,Mild,Mild,Moderate
freq,5,273,185,268,352,4446,1885,4446,2292,1814,2077,3257,1969

In [14]:
kingkong = data[data['Name'] == 'King Kong']
kingkong

,Name,Date,Rate,Votes,Genre,Duration,Type,Certificate,Episodes,Nudity,Violence,Profanity,Alcohol,Frightening
2084,King Kong,2005,7.2,"407,876","Action, Adventure, Drama",187,Film,PG-13,-,Mild,Moderate,Mild,Mild,Moderate
4207,King Kong,1976,5.9,"31,536","Adventure, Horror",134,Film,PG,-,Mild,Moderate,Mild,Mild,Moderate
4951,King Kong,1933,7.9,"82,705","Adventure, Horror, Sci-Fi",100,Film,Passed,-,Mild,Moderate,None,Mild,Moderate
5357,King Kong,1976,5.9,"31,536","Adventure, Horror",134,Film,PG,-,Mild,Moderate,Mild,Mild,Moderate
6101,King Kong,1933,7.9,"82,705","Adventure, Horror, Sci-Fi",100,Film,Passed,-,Mild,Moderate,None,Mild,Moderate

In [15]:
data=data.drop_duplicates()
data.shape

(5028, 14)